PROJECT_ROOT := ../../../
MODULE_FOLDER := src
VERILATOR_ROOT := $(PROJECT_ROOT)/electronics-verilator
PROJECT_NAME := SPI_S_TEST
SOURCES := src/SPI_S_TEST.sv
SIMFILES := *.cpp

include $(VERILATOR_ROOT)/verilator.mk
